name: Build and deploy roi-calculator
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy roi-calculator to (default: staging)"
        default: 'staging'
        required: true
        type: choice
        options:
          - staging
          - prod

run-name: Deploy to ${{ inputs.environment || 'staging' }} by @${{ github.actor }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"
          node-version-file: 'package.json'
      - name: build
        shell: bash
        env:
          CI: "false"
        run: |-
          npm ci
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        id: upload-artifacts
        with:
          name: build-output
          path: dist
          retention-days: 1

  deploy:
    uses: alphamind-co/devops/.github/workflows/build-and-deploy-service.yaml@main
    needs:
      - build
    with:
      stack-name: 'roi-calculator'
      environment: "${{ inputs.environment || 'staging' }}"
      artifacts-dir: 'dist'
    secrets:
      sc-config: "${{ secrets.SC_CONFIG }}"
